// Generated by js_of_ocaml 3.0.1
(function(d){"use strict";var
au=" : flags Open_text and Open_binary are not compatible",ae="Sys_error",at=224,as="Invalid_argument",t=1024,ar="fs",H="jsError",ad=57343,aq=512,ap="End_of_file",ao="Failure",ab="Undefined_recursive_module",ac=" : flags Open_rdonly and Open_wronly are not compatible",aa="([^/]*)",am="btn_click",an="Stack_overflow",g=128,b="",G="^",Y=" : file already exists",Z=2048,_=56320,$=240,f=248,ak="Not_found",al="undefined",X="Assert_failure",m="/",ai="Sys_blocked_io",aj="fd ",W="Out_of_memory",ah="Match_failure",af="Division_by_zero",ag="static/";function
bl(c,e){var
d=c.length,b=new
Array(d+1),a=0;for(;a<d;a++)b[a]=c[a];b[a]=e;return b}function
M(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
B(b,a){if(b.fun)return B(b.fun,a);var
c=b.length,d=a.length,e=c-d;if(e==0)return b.apply(null,a);else
if(e<0)return B(b.apply(null,M(a,0,c)),M(a,c,d-c));else
return function(c){return B(b,bl(a,c))}}var
a7=0;function
v(){return a7++}function
az(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bh(f){for(var
h=b,c=h,a,j,d=0,i=f.length;d<i;d++){a=f.charCodeAt(d);if(a<g){for(var
e=d+1;e<i&&(a=f.charCodeAt(e))<g;e++);if(e-d>aq){c.substr(0,1);h+=c;c=b;h+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==i)break;d=e}if(a<Z){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(g|a&63)}else
if(a<55296||a>=ad)c+=String.fromCharCode(at|a>>12,g|a>>6&63,g|a&63);else
if(a>=56319||d+1==i||(j=f.charCodeAt(d+1))<_||j>ad)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode($|a>>18,g|a>>12&63,g|a>>6&63,g|a&63)}if(c.length>t){c.substr(0,1);h+=c;c=b}}return h+c}function
a$(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
L(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=t,a-=t)f+=e.apply(null,M(c,d,Math.min(a,t)));return f}function
ax(a){if(a.t==2)a.c+=a$(a.l-a.c.length,"\0");else
a.c=L(a.c,0,a.c.length);a.t=0}function
bg(f){for(var
l=b,d=b,i,h,j,a,c=0,k=f.length;c<k;c++){h=f.charCodeAt(c);if(h<g){for(var
e=c+1;e<k&&(h=f.charCodeAt(e))<g;e++);if(e-c>aq){d.substr(0,1);l+=d;d=b;l+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(h<<6);if(h<at){a=i-12416;if(a<g)a=1}else{a=2;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(i<<6);if(h<$){a=i-925824;if(a<Z||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=f.charCodeAt(c))&-64)==g&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),_+(a&1023));else
d+=String.fromCharCode(a);if(d.length>t){d.substr(0,1);l+=d;d=b}}return l+d}function
bf(a){switch(a.t){case
9:return a.c;default:ax(a);case
0:if(az(a.c)){a.t=9;return a.c}a.t=8;case
8:return bg(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return bf(this)};function
K(a){var
b=9;if(!az(a))b=8,a=bh(a);return new
n(b,a,a.length)}function
a9(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
aE(c,b){a9(c,a(b))}var
c=[0];function
j(a){aE(c.Sys_error,a)}var
o=new
Array();function
a3(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
d=c.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=b;return 0}if(d.process&&d.process.cwd)var
u=d.process.cwd().replace(/\\/g,m);else
var
u="/static";if(u.slice(-1)!==m)u+=m;function
a2(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=u+a;var
e=a.split(m),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
a8(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
bb(a){return new
n(4,a,a.length)}function
ay(a){aE(c.Invalid_argument,a)}function
aH(){ay("index out of bounds")}function
bd(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
ba(b,a){if(a>>>0>=b.l)aH();return bd(b,a)}function
p(a){if(a<0)ay("String.create");return new
n(a?2:9,b,a)}function
aB(a){return a.l}function
J(b){if(d.Uint8Array)var
c=new(d.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)c[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)c[a]=0;b.c=c;b.t=4;return c}function
A(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?L(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?L(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)J(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
av(){}function
e(a){this.data=a}e.prototype=new
av();e.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);A(b,0,this.data,0,a)};e.prototype.length=function(){return aB(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;A(f,0,this.data,0,c)}A(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();A(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return ba(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
e(c[1])}};h.prototype.exists=function(a){if(a==b)return 1;var
d=a+m,e=new
RegExp(G+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+m,h=new
RegExp(G+g+aa),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+m,f=new
RegExp(G+e+aa),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+ac);if(b.text&&b.binary)j(this.nm(a)+au);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+Y);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(p(0));return this.content[a]}else
a8(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+Y);if(b
instanceof
n)this.content[c]=new
e(b);else
if(b
instanceof
Array)this.content[c]=new
e(bb(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
e(d)}};h.prototype.constructor=h;function
aw(a){if(a.t!=4)J(a);return a.c}function
be(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}J(a)}a.c[c]=b;return 0}function
bc(b,a,c){if(a>>>0>=b.l)aH();return be(b,a,c)}var
I=d.Buffer;function
l(a){this.fs=require(ar);this.fd=a}l.prototype=new
av();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,f){var
a=aw(b);if(!a
instanceof
d.Uint8Array)a=new(d.Uint8Array)(a);var
e=new
I(a);this.fs.writeSync(this.fd,e,c,f,g);return 0};l.prototype.read=function(h,e,c,g){var
a=aw(e);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
f=new
I(a);this.fs.readSync(this.fd,f,c,g,h);for(var
b=0;b<g;b++)bc(e,c+b,f[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(d.Uint8Array)(1),a=new
I(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(ar);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=u.match(/[^\/]*\//)[0],w=[];if(typeof
module!==al&&module.exports&&typeof
require!==al)w.push({path:q,device:new
k(q)});else
w.push({path:q,device:new
h(q)});w.push({path:q+ag,device:new
h(q+ag)});function
bm(b){var
f=a2(b),b=f.join(m),e=b+m,c;for(var
d=0;d<w.length;d++){var
a=w[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aG(e,f){var
b=o[e],d=a(f),c=aB(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
bj(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
bk(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
C(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
bn(d,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(d.toString()+ac);if(a.text&&a.binary)j(d.toString()+au);var
e=bm(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return C(g+1,aG,f,a)}C(0,aG,new
e(p(0)));C(1,bk,new
e(p(0)));C(2,bj,new
e(p(0)));function
a4(d){var
b=c.fds[d];if(b.flags.wronly)j(aj+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
aA(e){var
d=c.fds[e];if(d.flags.rdonly)j(aj+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
a5(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
a6(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(d,b,a){c[d+1]=b;if(a)c[a]=b}var
aD={};function
a1(a){if((a.t&6)!=0)ax(a);return a.c}function
a_(a,b){aD[a1(a)]=b;return 0}function
aF(a){return a}function
aC(a){return aD[a]}function
bi(a){if(a
instanceof
Array)return a;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))return aF(c.Stack_overflow);if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))return aF(c.Stack_overflow);if(a
instanceof
d.Error&&aC(H))return[0,aC(H),a];return[0,c.Failure,K(String(a))]}function
V(a,b){return a.length==1?a(b):B(a,[b])}var
O=[f,a(ae),-2],N=[f,a(ao),-3],P=[f,a(ak),-7];i(11,[f,a(ab),-12],ab);i(10,[f,a(X),-11],X);i(9,[f,a(ai),-10],ai);i(8,[f,a(an),-9],an);i(7,[f,a(ah),-8],ah);i(6,P,ak);i(5,[f,a(af),-6],af);i(4,[f,a(ap),-5],ap);i(3,[f,a(as),-4],as);i(2,N,ao);i(1,O,ae);i(0,[f,a(W),-1],W);v(0);a4(0);aA(1);aA(2);v(0);v(0);var
Q=[0,0],aN=a("Js.Error"),aQ=a("erreur"),aP=a(am),aR=a("btn_alert"),aU=a(am),aW=a("click_number"),aY=a("btn_reset");function
R(a){Q[1]=[0,a,Q[1]];return 0}var
r=d,x=null,y=true,aM=r.Array,S=[f,aN,v(0)],D=[0,S,{}],aK=undefined,aL=false,aJ=a6(D)===f?D:D[1];a_(a(H),aJ);(function(a){throw a});R(function(a){return a[1]===S?[0,K(a[2].toString())]:0});R(function(a){return a
instanceof
aM?0:[0,K(a.toString())]});function
E(c){return function(a){if(1-(a==x?1:0)){var
d=V(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=V(c,e);if(1-(b|0))e.returnValue=b;return b}}var
aO=r.document;function
s(b){var
a=aO.getElementById(b.toString());if(a==x)throw P;return a}v(0);r.HTMLElement===aK;var
z=[0,0],T=s(aP),F=T.tagName.toLowerCase()==="button"?T:x;if(F==x){r.alert("elem n'existe pas");throw[0,N,aQ]}var
aS=s(aR),aT=E(function(a){r.alert("Alert");return y}),aV=s(aU),U=s(aW),aX=E(function(d){z[1]=z[1]+1|0;var
c=z[1];U.innerHTML=a(b+c).toString();if(10===c)F.disabled=y;return y}),aZ=s(aY),a0=E(function(a){z[1]=0;U.innerHTML="0";F.disabled=aL;return y});aS.onclick=aT;aV.onclick=aX;aZ.onclick=a0;function
aI(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{a3(d)}catch(a){a=bi(a);if(a[1]!==O)throw a}var
a=c;continue}return 0}}aI(a5(0));return}(function(){return this}()));
